---
title: "Untitled"
author: "qihan"
date: "2024-01-26"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("reticulate")
require("reticulate")
library(reticulate)
library(dplyr)
import("scipy")
pd <- import("pandas")
np <- import("numpy")
source("R_gas_functions.R")
library(pracma)
library(mvtnorm) 
```
```{r}
data_N5236 <- pd$read_pickle("N5236_25_1_2024.pkl")
data_mgs    <- pd$read_pickle("N5236_mgs_data.pkl")
data_mgs$CO21_mgd = log(data_mgs$CO21_mgd)
```



```{r}
idx = is.finite(data_N5236$Z_N2S2Ha)
data_N5236 = data_N5236[(idx == 1), ]
data_N5236 = subset(data_N5236, data_N5236$N2_BPT < 1) 

set.seed(2024)
sample = sample.int(n = nrow(data_mgs), size = floor(0.02*nrow(data_mgs)), replace = F)
d_test = data_mgs[sample, ]
```


```{r}
N5236_coor = To_xy_coor(data_N5236$RA, data_N5236$DEC, RA_gal = 204.2516509, 
                        DEC_gal = -29.86547, PA_gal = 54, i_gal = 12.50496329,
                        D_gal = 4.89778819)
data_N5236$X <- N5236_coor[,1]
data_N5236$Y <- N5236_coor[,2]


# add an index
data_N5236 <- cbind(data_N5236, index = 1:dim(data_N5236)[1])
data_mgs <- cbind(data_mgs, index = 1:dim(data_mgs)[1]) 

plot(data_N5236$X, data_N5236$Y, cex = 0.3, col = "red")
points(d_test$X, d_test$Y, cex = 0.3)
```

```{r}
a = 5.5
b = -5.5
c = 6
d = -6
Localdata = c()
for (i in 1:dim(data_N5236)[1]){
  if (data_N5236[i,]$X < a){
    if (data_N5236[i,]$X > b){
      if (data_N5236[i,]$Y < c){
        if (data_N5236[i,]$Y > d){
          Localdata = rbind(Localdata, data_N5236[i,])
        }
      }
    }
  }
}

Localgas = c()
for (i in 1:dim(d_test)[1]){
  if (d_test[i,]$X < a){
    if (d_test[i,]$X > b){
      if (d_test[i,]$Y < c){
        if (d_test[i,]$Y > d){
          Localgas = rbind(Localgas, d_test[i,])
        }
      }
    }
  }
}
plot(Localgas$X, Localgas$Y, cex = 0.3)
points(Localdata$X, Localdata$Y, cex = 0.3, col = "red", pch = 16)
```


```{r}
Local_gas  = Localgas
Local_data = Localdata
dim(Local_gas)
dim(Local_data)
```
```{r}
D_gas = deprojected_distances(Local_gas$RA, Local_gas$DEC, Local_gas$RA, Local_gas$DEC)
D_data = deprojected_distances(Local_data$RA, Local_data$DEC, Local_data$RA, Local_data$DEC)
D_data_to_gas = deprojected_distances(Local_data$RA, Local_data$DEC, Local_gas$RA, Local_gas$DEC)
```

```{r}
y_gas = as.matrix(select(Local_gas, c("CO21_mgd")))
X_gas = as.matrix(cbind(1, select(Local_gas, c("proj_dist"))))
```


```{r}
gas_coor = cbind(Local_gas$X, Local_gas$Y)
v_gas = cbind(gas_coor, y_gas, X_gas)
V_gas = as.geodata(v_gas, coords.col = 1:2, data.col = 3, covar.col = 4:5, covar.names = c("int", "dist")) 
vario = variog(V_gas, max.dist=2, trend = ~ 1 + dist)
plot(vario,xlab = "h", ylab = "gamma(h)")
```

```{r}
source_python("BFuns.py")

res1 = MLE_fit_gas(y = y_gas, X = X_gas, D = D_gas, cov_model = "Exp")
res1
```
```{r}
thetahat1 = res1[[1]] 
betahat1  = res1[[4]] 
Sigma1 = thetahat1[2]*exp(-D_gas/thetahat1[1]) 
diag(Sigma1) = thetahat1[2] + thetahat1[3]
d0 = cbind(1, Local_data$proj_dist)
cmat1 = thetahat1[2]*exp(-D_data_to_gas/thetahat1[1]) 
pl1 = as.matrix(d0)%*%betahat1 
pe1 = cmat1%*% solve(Sigma1)%*%(y_gas - X_gas%*%betahat1)
w = pl1 + pe1
```






```{r}
new_data = Local_data
new_data$w = w
```

```{r}
set.seed(2024)
idx = sample.int(n = nrow(new_data), size = floor(0.2*nrow(new_data)), replace = F)
test= new_data[idx, ]
train = new_data[-idx, ] 
```

```{r}
Wtrain = as.matrix(cbind(1, select(train, c("w", "proj_dist"))))
Ytrain = as.matrix(select(train, c("Z_N2S2Ha")))
```


```{r}
beta_ols = solve(t(Wtrain)%*%Wtrain)%*%t(Wtrain)%*%Ytrain
```



```{r}
res2 = MLE_fit(y = Ytrain, X = Wtrain, D = D_data[-idx,-idx], cov_model = "Exp")
res2
```
theta_est, suc, nll, beta_est, beta_var

```{r}
thetahat2 = res2[[1]] # theta_est
betahat2  = res2[[4]] # beta_est
Sigma2 = thetahat2[2]*exp(-D_data[-idx,-idx]/thetahat2[1]) 
d1 = cbind(1, test$w, test$proj_dist)
cmat2 = thetahat2[2]*exp(-D_data[idx,-idx]/thetahat2[1]) 
pl2 = as.matrix(d1)%*%betahat2       
```

```{r}
pe2 = cmat2%*% solve(Sigma2)%*%(Ytrain - Wtrain%*%betahat2) 
pred_Y = pl2 + pe2
(RMSE_geo_dist_kr <- sqrt(mean((pred_Y - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_kr <- mean(abs(pred_Y - test$Z_N2S2Ha)))
```


```{r}
d1 = cbind(1, test$w, test$proj_dist)
pols = as.matrix(d1)%*%beta_ols
(RMSE_geo_dist_ols <- sqrt(mean((pols - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_ols <- mean(abs(pols - test$Z_N2S2Ha)))
```

```{r}
source("SDCal_modified.R")
sdout1 = SDCal(D_gas, thetahat1, 'Exp', nug = 1)
```



```{r}
sdout2 = SDCal(D_data[-idx,-idx], thetahat2, 'Exp', nug = 1)
```



```{r}
inv_Sigma = solve(Sigma1)
Cz0 = (thetahat1[2] + thetahat1[3])*exp(-D_data/thetahat1[1]) 
pc = as.matrix(d0) - cmat1%*%inv_Sigma%*%X_gas
CovU = Cz0 - cmat1%*%inv_Sigma%*%t(cmat1) + (pc)%*%solve(t(X_gas)%*%inv_Sigma%*%X_gas)%*%t(pc)

```


```{r}
source_python("BFuns.py")
source_python("Internal_Fun.py")

res3 = MLE_fit_GLS(y = Ytrain, X = Wtrain, D = D_data[-idx,-idx], kSigma = CovU[-idx,-idx]*beta_ols[2]^2, cov_model = "Exp")
res3
```




```{r}
thetahat3 = res3[[1]] # theta_est
CovE_GLS = thetahat3[2]*exp(-D_data[-idx,-idx]/thetahat3[1]) 
CovUBE_GLS = CovU[-idx,-idx]*beta_ols[2]^2 + CovE_GLS
beta_RBEGLS_initial = solve(t(Wtrain)%*%solve(CovUBE_GLS)%*%Wtrain)%*%t(Wtrain)%*%solve(CovUBE_GLS)%*%Ytrain
```

```{r}
#CovE_GLS = theta_RBEGLS[2]*CorE_GLS
#CovUB = CovU[-idx,-idx]*beta_RBEGLS[2]^2 
#CovUBE_GLS = CovUB + CovE_GLS

d1 = cbind(1, test$w, test$proj_dist)
cmat3 = thetahat3[2]*exp(-D_data[idx,-idx]/thetahat3[1]) 
pl3 = as.matrix(d1)%*%beta_RBEGLS_initial 


pe3 = cmat3%*% solve(CovUBE_GLS)%*%(Ytrain - Wtrain%*%beta_RBEGLS_initial) 
pred3 = pl3 + pe3
(RMSE_geo_dist_3 <- sqrt(mean((pred3 - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_3 <- mean(abs(pred3 - test$Z_N2S2Ha)))
```


```{r}
res4 = MLE_fit_GLS(y = Ytrain, X = Wtrain, D = D_data[-idx,-idx], kSigma = CovU[-idx,-idx]*beta_RBEGLS_initial[2]^2, cov_model = "Exp")
res4

thetahat4 = res4[[1]] # theta_est
CovE_GLS4 = thetahat4[2]*exp(-D_data[-idx,-idx]/thetahat4[1]) 
CovUBE_GLS4 = CovU[-idx,-idx]*beta_RBEGLS_initial[2]^2 + CovE_GLS4
beta_RBEGLS_4 = solve(t(Wtrain)%*%solve(CovUBE_GLS4)%*%Wtrain)%*%t(Wtrain)%*%solve(CovUBE_GLS4)%*%Ytrain
```

```{r}
res5 = MLE_fit_GLS(y = Ytrain, X = Wtrain, D = D_data[-idx,-idx], kSigma = CovU[-idx,-idx]*beta_RBEGLS_4[2]^2, cov_model = "Exp")
res5

thetahat5 = res5[[1]] # theta_est
CovE_GLS5 = thetahat5[2]*exp(-D_data[-idx,-idx]/thetahat5[1]) 
CovUBE_GLS5 = CovU[-idx,-idx]*beta_RBEGLS_4[2]^2 + CovE_GLS5
beta_RBEGLS_5 = solve(t(Wtrain)%*%solve(CovUBE_GLS5)%*%Wtrain)%*%t(Wtrain)%*%solve(CovUBE_GLS5)%*%Ytrain
```
```{r}
res6 = MLE_fit_GLS(y = Ytrain, X = Wtrain, D = D_data[-idx,-idx], kSigma = CovU[-idx,-idx]*beta_RBEGLS_5[2]^2, cov_model = "Exp")
res6

thetahat6 = res6[[1]] # theta_est
CovE_GLS6 = thetahat6[2]*exp(-D_data[-idx,-idx]/thetahat6[1]) 
CovUBE_GLS6 = CovU[-idx,-idx]*beta_RBEGLS_5[2]^2 + CovE_GLS6
beta_RBEGLS_6 = solve(t(Wtrain)%*%solve(CovUBE_GLS6)%*%Wtrain)%*%t(Wtrain)%*%solve(CovUBE_GLS6)%*%Ytrain
```
```{r}
CovUB6 = CovU[-idx,-idx]*beta_RBEGLS_6[2]^2 

CovUBE_GLS6 = CovUB6 + CovE_GLS6
A1 = solve(t(Wtrain)%*%solve(CovUBE_GLS6)%*%Wtrain)

varbeta_cl0 = diag(A1)
```






```{r}
d1 = cbind(1, test$w, test$proj_dist)
cmat6 = thetahat6[2]*exp(-D_data[idx,-idx]/thetahat6[1]) 
pl6 = as.matrix(d1)%*%beta_RBEGLS_6


pe6 = cmat6%*% solve(CovUBE_GLS6)%*%(Ytrain - Wtrain%*%beta_RBEGLS_6) 
pred6 = pl6 + pe6
(RMSE_geo_dist_6 <- sqrt(mean((pred6 - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_6 <- mean(abs(pred6 - test$Z_N2S2Ha)))
```

```{r}
head(pred6)
```

```{r}
inv_CovUBE_GLS6 = solve(CovUBE_GLS6)
```

```{r}
Cz6 =  thetahat6[2]*exp(-D_data[idx,idx]/thetahat6[1]) 

pc6 = as.matrix(d1) - cmat6%*%inv_CovUBE_GLS6%*%Wtrain


Cov6 = Cz6 - cmat6%*%inv_CovUBE_GLS6%*%t(cmat6) + (pc6)%*%solve(t(Wtrain)%*%inv_CovUBE_GLS6%*%Wtrain)%*%t(pc6)

```


```{r}
head(diag(Cov6))
```
```{r}
CI6 = cbind(pred6-2.576*sqrt(diag(Cov6)), pred6 + 2.576*sqrt(diag(Cov6)))
head(CI6)
head(test$Z_N2S2Ha)
```
```{r}
v = 0
for (s in 1:length(test$Z_N2S2Ha)){
  if (test$Z_N2S2Ha[s] > CI6[s,][1] ){
    if (test$Z_N2S2Ha[s] < CI6[s,][2]){
      v = v + 1
    }
  }else{
    v = v + 0
  }
}
print(length(test$Z_N2S2Ha))
print(v)
print(v/length(test$Z_N2S2Ha))
```
```{r}
source_python("BFuns.py")
source_python("Internal_Fun.py")
```




# Proposed method 1:

```{r}
z0 = beta_RBEGLS_6[1]  + beta_RBEGLS_6[2]*betahat1[1]
z1 = beta_RBEGLS_6[2]*betahat1[2]
 
zeta = t(cbind(z0,z1))

out_tau = MLE_fit_CS(CovUBE_GLS6, D_data[idx,idx], zeta, Ytrain, d0[-idx,])
```









```{r}
CovT = 2*0.002442122*diag(dim(CovUBE_GLS6)[1])
```

```{r}
#CovUB6 = CovU[-idx,-idx]*beta_RBEGLS_6[2]^2 

CovUBE_GLS6T = CovUB6 + CovE_GLS6 + CovT
A1T = solve(t(Wtrain)%*%solve(CovUBE_GLS6T)%*%Wtrain)

varbeta_cl0T = diag(A1T)
```


```{r}
d1 = cbind(1, test$w, test$proj_dist)
cmat6T = thetahat6[2]*exp(-D_data[idx,-idx]/thetahat6[1]) 
pl6T = as.matrix(d1)%*%beta_RBEGLS_6


pe6T = cmat6T%*% solve(CovUBE_GLS6T)%*%(Ytrain - Wtrain%*%beta_RBEGLS_6) 
pred6T = pl6T + pe6T
(RMSE_geo_dist_6T <- sqrt(mean((pred6T - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_6T <- mean(abs(pred6T - test$Z_N2S2Ha)))
```

```{r}
inv_CovUBE_GLS6T = solve(CovUBE_GLS6T)
```

```{r}
Cz6T =  thetahat6[2]*exp(-D_data[idx,idx]/thetahat6[1]) 

pc6T = as.matrix(d1) - cmat6T%*%inv_CovUBE_GLS6T%*%Wtrain


Cov6T = Cz6T - cmat6T%*%inv_CovUBE_GLS6T%*%t(cmat6T) + (pc6T)%*%solve(t(Wtrain)%*%inv_CovUBE_GLS6T%*%Wtrain)%*%t(pc6T)

```
```{r}
CI6T = cbind(pred6T-2.576*sqrt(diag(Cov6T)), pred6T + 2.576*sqrt(diag(Cov6T)))
head(CI6T)
head(test$Z_N2S2Ha)
```


```{r}
v = 0
for (s in 1:length(test$Z_N2S2Ha)){
  if (test$Z_N2S2Ha[s] > CI6T[s,][1] ){
    if (test$Z_N2S2Ha[s] < CI6T[s,][2]){
      v = v + 1
    }
  }else{
    v = v + 0
  }
}
print(length(test$Z_N2S2Ha))
print(v)
print(v/length(test$Z_N2S2Ha))
```



```{r}
source("BFuns_CS.R")
out_tau1 = MLE.fit_CS(CovUBE_GLS6, D_data[idx,idx], zeta, Ytrain, d0[-idx,], c(0.1), "LB",c(0.001), c(5))
```













```{r}
thetahat2 = res2[[1]] # theta_est
betahat2  = res2[[4]] # beta_est
Sigma2 = thetahat2[2]*exp(-D_data[-idx,-idx]/thetahat2[1]) 
d1 = cbind(1, test$w, test$proj_dist)
cmat2 = thetahat2[2]*exp(-D_data[idx,-idx]/thetahat2[1]) 
pl2 = as.matrix(d1)%*%betahat2       
```

```{r}
pe2 = cmat2%*% solve(Sigma2)%*%(Ytrain - Wtrain%*%betahat2) 
pred_Y = pl2 + pe2
(RMSE_geo_dist_kr <- sqrt(mean((pred_Y - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_kr <- mean(abs(pred_Y - test$Z_N2S2Ha)))
```


```{r}
inv_Sigma2 = solve(Sigma2)
```

```{r}
Cz2 =  thetahat2[2]*exp(-D_data[idx,idx]/thetahat2[1]) 

pc2 = as.matrix(d1) - cmat2%*%inv_Sigma2%*%Wtrain


Cov2 = Cz2 - cmat2%*%inv_Sigma2%*%t(cmat2) + (pc2)%*%solve(t(Wtrain)%*%inv_Sigma2%*%Wtrain)%*%t(pc2)

```



```{r}
CI2 = cbind(pred_Y-2.576*sqrt(diag(Cov2)), pred_Y + 2.576*sqrt(diag(Cov2)))
head(CI2)
head(test$Z_N2S2Ha)
```


```{r}
v = 0
for (s in 1:length(test$Z_N2S2Ha)){
  if (test$Z_N2S2Ha[s] > CI2[s,][1] ){
    if (test$Z_N2S2Ha[s] < CI2[s,][2]){
      v = v + 1
    }
  }else{
    v = v + 0
  }
}
print(length(test$Z_N2S2Ha))
print(v)
print(v/length(test$Z_N2S2Ha))
```


```{r}
beta_ols = solve(t(Wtrain)%*%Wtrain)%*%t(Wtrain)%*%Ytrain

model1 = lm(Ytrain~Wtrain-1)
summary(model1)
```
```{r}
d1 = cbind(1, test$w, test$proj_dist)
pols = as.matrix(d1)%*%beta_ols
head(pols)
```
```{r}
CI1 = cbind(pols-2.576*0.09611, pols + 2.576*0.09611)
head(CI1)
head(test$Z_N2S2Ha)
```

```{r}
v = 0
for (s in 1:length(test$Z_N2S2Ha)){
  if (test$Z_N2S2Ha[s] > CI1[s,][1] ){
    if (test$Z_N2S2Ha[s] < CI1[s,][2]){
      v = v + 1
    }
  }else{
    v = v + 0
  }
}
print(length(test$Z_N2S2Ha))
print(v)
print(v/length(test$Z_N2S2Ha))
```











```{r}
Wtrain2 = as.matrix(cbind(1, select(train, c("proj_dist"))))
```

```{r}
source_python("BFuns.py")
source_python("Internal_Fun.py")
res_d = MLE_fit(y = Ytrain, X = Wtrain2, D = D_data[-idx,-idx], cov_model = "Exp")
res_d
```
```{r}
thetahat_d = res_d[[1]] # theta_est
betahat_d  = res_d[[4]] # beta_est
Sigma_d = thetahat_d[2]*exp(-D_data[-idx,-idx]/thetahat_d[1]) 
d1 = cbind(1, test$proj_dist)
cmat_d = thetahat_d[2]*exp(-D_data[idx,-idx]/thetahat_d[1]) 
pld = as.matrix(d1)%*%betahat_d       
```

```{r}
ped = cmat_d%*% solve(Sigma_d)%*%(Ytrain - Wtrain2%*%betahat_d) 
pred_Yd = pld + ped
(RMSE_geo_dist_kr_d <- sqrt(mean((pred_Yd - test$Z_N2S2Ha)^2)))
(MAD_geo_dist_kr_d <- mean(abs(pred_Yd - test$Z_N2S2Ha)))
```





```{r}
png(filename="Z_gas1.png", width=600, height=400)
plot(data_N5236$X, data_N5236$Y, cex = 0.3, col = "red", main = "Metallicity Locations and Molecular gas surface density Locations", xlab = "X (kpcs)", ylab = "Y (kpcs)")
points(d_test$X, d_test$Y, cex = 0.3)
```


```{r}
png(filename="Z_gas2.png", width=600, height=400)
plot(Localdata$X, Localdata$Y, cex = 0.3, , col = "red", main = "Metallicity Locations and Molecular gas surface density Locations", xlab = "X (kpcs)", ylab = "Y (kpcs)")
points(Localgas$X, Localgas$Y, cex = 0.3)
```














